---
- name: Download Prometheus tarball
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v2.46.0/prometheus-2.46.0.linux-amd64.tar.gz"
    dest: /tmp/prometheus.tar.gz
    mode: "0644"
  tags: prometheus

- name: Extract Prometheus tarball
  ansible.builtin.unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /usr/local/bin/
    remote_src: yes
    creates: /usr/local/bin/prometheus-2.46.0.linux-amd64/prometheus
  tags: prometheus

- name: Create Prometheus user
  ansible.builtin.user:
    name: prometheus
    shell: /usr/sbin/nologin
    system: yes
    create_home: no
  tags: prometheus

- name: Create Prometheus config directory
  ansible.builtin.file:
    path: /etc/prometheus
    state: directory
    owner: prometheus
    group: prometheus
    mode: "0755"
  tags: prometheus

- name: Create Prometheus data directory
  ansible.builtin.file:
    path: /var/lib/prometheus
    state: directory
    owner: prometheus
    group: prometheus
    mode: "0755"
  tags: prometheus

- name: Create Prometheus rules directory
  ansible.builtin.file:
    path: /etc/prometheus/rules
    state: directory
    owner: prometheus
    group: prometheus
    mode: "0755"
  tags: prometheus

- name: Copy Prometheus configuration
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: "0644"
  notify: restart prometheus
  tags: prometheus

- name: Copy Prometheus alerting rules
  ansible.builtin.copy:
    src: rules/node_alerts.yml
    dest: /etc/prometheus/rules/alerts.yml
    owner: prometheus
    group: prometheus
    mode: "0644"
  notify: restart prometheus
  tags: prometheus


- name: Copy Prometheus systemd service
  ansible.builtin.template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload systemd
  tags: prometheus

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  tags: prometheus

- name: Enable and start Prometheus service
  ansible.builtin.systemd:
    name: prometheus
    enabled: yes
    state: started
  tags: prometheus
